-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 14:03:02 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `content` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsers_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTypesUsers_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users_has_types` (
  `user_id` INT NOT NULL,
  `type_user_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `type_user_id`),
  INDEX `fk_Users_has_TypesUsers_TypesUsers1_idx` (`type_user_id` ASC),
  INDEX `fk_Users_has_TypesUsers_Users_idx` (`user_id` ASC),
  CONSTRAINT `fk_Users_has_TypesUsers_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_TypesUsers_TypesUsers1`
    FOREIGN KEY (`type_user_id`)
    REFERENCES `mydb`.`type_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
