-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 06:27:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `content` VARCHAR(200) NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TypesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TypesUsers` (
  `idTypesUsers` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypesUsers`),
  UNIQUE INDEX `idTypesUsers_UNIQUE` (`idTypesUsers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_TypesUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_TypesUsers` (
  `Users_idUsers` INT NOT NULL,
  `TypesUsers_idTypesUsers` INT NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `TypesUsers_idTypesUsers`),
  INDEX `fk_Users_has_TypesUsers_TypesUsers1_idx` (`TypesUsers_idTypesUsers` ASC),
  INDEX `fk_Users_has_TypesUsers_Users_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Users_has_TypesUsers_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_TypesUsers_TypesUsers1`
    FOREIGN KEY (`TypesUsers_idTypesUsers`)
    REFERENCES `mydb`.`TypesUsers` (`idTypesUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
