    <div class="jumbotron" style="margin-top: 50px;margin-bottom: 50px;">
    <h1>Bem vindo ao <span class="zf-green">Legalizer ERP</span></h1>

    <p>
        Especialista em soluções <i>empresariais</i> e <i>industriais</i>, o Legalizer ERP é uma solução inteligente que
        disponibiliza módulos independentes e funcionais para gestão dentro dos padrões exigido pelo orgão legalizador.

    </p>

</div>

